openapi: 3.0.0
info:
  title: Cadastro de Usuários
  version: 1.0.0
  description: API para gerenciamento de usuários.
servers:
  - url: http://localhost:8080/cadastro
paths:
  /:
    post:
      summary: Cadastra uma pessoa
      description: Cadastra uma pessoa passando os campos.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                email:
                  type: string
                idade:
                  type: integer
              required:
                - nome
                - email
                - idade
      responses:
        '200':
          description: Retorna a mensagem 'Cadastro realizado'.
        '400':
          description: Ocorreu um erro durante o cadastro.

  /{id}:
    get:
      summary: Busca uma pessoa por ID
      description: Busca uma pessoa por um ID existente.
      parameters:
        - name: id
          in: path
          required: true
          description: ID do usuário a ser buscado.
          schema:
            type: integer
      responses:
        '200':
          description: Retorna uma pessoa existente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  nome:
                    type: string
                  email:
                    type: string
                  idade:
                    type: integer
        '404':
          description: Este usuário não existe.

    delete:
      summary: Deleta um usuário existente
      description: Deleta um usuário existente passando o ID.
      parameters:
        - name: id
          in: path
          required: true
          description: ID do usuário a ser deletado.
          schema:
            type: integer
      responses:
        '200':
          description: Usuário deletado com sucesso.
        '404':
          description: Este usuário não existe.

    put:
      summary: Atualiza um usuário existente
      description: Atualiza um usuário existente passando o ID.
      parameters:
        - name: id
          in: path
          required: true
          description: ID do usuário a ser atualizado.
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                email:
                  type: string
                idade:
                  type: integer
              required:
                - nome
                - email
                - idade
      responses:
        '200':
          description: Retorna o usuário atualizado.
        '404':
          description: ID não encontrado.

  /all:
    get:
      summary: Retorna todos os usuários cadastrados
      description: Retorna todos os usuários cadastrados no banco de dados.
      responses:
        '200':
          description: Retorna todos os usuários cadastrados.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    nome:
                      type: string
                    email:
                      type: string
                    idade:
                      type: integer
